### ISSUE TITLE
integration testing: 0.20230405.093348-dev_main : fod scan start-sast throw error- No Enum constant

### ISSUE THREAD

**Issue by rohitbaryha1** [fortify/fcli#279] opened 2023-04-06 06:30 UTC
While starting SAST scan, throw the error of No Enum Constant for _--remediation-preference_ parameter.

**Here is the log:**
command: fod scan start-sast
arg: --entitlement-id=393 --notes='notes for test cases' --file='C:\Users\RohKumar\Downloads\package.zip' --entitlement-preference=SubscriptionFirstThenSingleScan --remediation-preference=NonRemediationScanOnly --in-progress-action=Queue INT_T_App1:INT_T_App1_Release1
Output: 
Running Command: ./fcli-beta.exe fod scan start-sast --entitlement-id=393 --notes='notes for test cases' --file='C:\Users\RohKumar\Downloads\package.zip' --entitlement-preference=SubscriptionFirstThenSingleScan --remediation-preference=NonRemediationScanOnly
 --in-progress-action=Queue INT_T_App1:INT_T_App1_Release1
./fcli-beta.exe : java.lang.IllegalArgumentException: **No enum constant com.fortify.cli.fod.util.FoDEnums$EntitlementPreferenceType.NonRemediationScanOnly**
At line:1 char:1
+ ./fcli-beta.exe fod scan start-sast --entitlement-id=393 --notes='not ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (java.lang.Illeg...diationScanOnly:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
	at java.base@17.0.6/java.lang.Enum.valueOf(Enum.java:155)
	at com.fortify.cli.fod.util.FoDEnums$EntitlementPreferenceType.valueOf(FoDEnums.java:87)
	at com.fortify.cli.fod.entity.scan_sast.helper.FoDSastScanHelper.startScan(FoDSastScanHelper.java:69)
	at com.fortify.cli.fod.entity.scan_sast.cli.cmd.FoDSastScanStartCommand.getJsonNode(FoDSastScanStartCommand.java:133)
	at com.fortify.cli.fod.output.cli.AbstractFoDJsonNodeOutputCommand.getJsonNode(AbstractFoDJsonNodeOutputCommand.java:11)
	at com.fortify.cli.common.output.cli.cmd.AbstractOutputCommand.run(AbstractOutputCommand.java:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2104)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2539)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2531)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2493)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2351)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2495)
	at picocli.CommandLine.execute(CommandLine.java:2248)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:86)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:68)

**Comment by rsenden** [comment] 2023-04-06 09:29
I think the root cause of this issue is that `FoDSastScanStartCommand` incorrectly mixes entitlement preference and remediation preference, effectively doing the following when creating an `FoDStartSastScanRequest` instance:

```
new FoDStartSastScanRequest().setEntitlementPreferenceType(remediationScanType.getRemediationScanPreferenceType().name())
```

Apart from setting the wrong value for entitlement preference, it seems like remediation scan preference is never set on `FoDStartSastScanRequest`. Of course, `FoDSastScanStartCommand` can be updated to call the proper setters, however `FoDStartSastScanRequest` can be improved to avoid mistakes like this (before implementing any of this, please see last bullet point for potentially better alternative approach):

* As a general convention, setters should always have `void` return type; builder-style methods returning `this` shouldn't have the `set` prefix. For example: `public FoDStartSastScanRequest setEntitlementPreferenceType` should be renamed to `public FoDStartSastScanRequest entitlementPreferenceType(...)`. 

* Default values should be handled differently; depending on the wanted behavior:
     * The mixins in `FoDRemediationScanPreferenceTypeOptions` could set default option values, such that the returned enum value is never null; this is probably the best approach if all commands using these mixins should always have the same default value.
     * Alternatively, `FoDStartSastScanRequest` could handle default values, either setting a default value if `null` is passed to the setter, and/or setting default values on its fields in case the setter never gets called.

* The builder-style setter methods in `FoDStartSastScanRequest` methods should take the actual enum values as parameter, not a simple `String`, i.e.:

        public FoDStartSastScanRequest entitlementPreferenceType(EntitlementPreferenceType type) {
            this.entitlementPreferenceType = type.name(); // If necessary, handle null values; see previous point
            return this;
        }

* Some of the method parameters/field names in `FoDStartSastScanRequest` are misspelled, i.e. `remdiationScanPreferenceType` instead of `remediationScanPreferenceType`; this should be fixed

* As an alternative to most of the above, the following approach may potentially result in even better code:
     * Change the various enums in FoDEnums to use Jackson annotations like `@JsonValue` to have Jackson serialize/deserialize enum values to/from FoD values (see https://www.baeldung.com/jackson-serialize-enums) when generating requests and reading responses.
     * Have the fields in `FoDStartSastScanRequest` (and similar request/response classes) use the proper enum type instead of simple Strings/primitive types; the Jackson annotations on the enums will take care of proper serialization of enum values to FoD values
     * Remove the setters from `FoDStartSastScanRequest`, and add an `@Builder` annotation instead
     * Update `FoDSastScanStartCommand` to call `FoDStartSastScanRequest.builder()...<call builder methods>...build()`

These changes will make the code in `FoDSastScanStartCommand` much easier (no null checks necessary, no need to call the `name()` method on every enum value) and much safer as there is no more risk of passing incorrect option values to the request object).

**FoDEnums**

A somewhat similar issues exist in the various enums in FoDEnums, where switch-statements are used to map enum values to FoD values and vice versa. Doing manual mappings like this is error-prone. 

For example, suppose FoD adds a new entitlement preference type, someone adds this value to the enum, but forgets to update the switch-statements. Now, when mapping enum values to FoD values or vice versa, the `default` case in the switch-statements will be used, resulting in an incorrect mapping.

To improve maintainability of this code and make it less error-prone, mapping should be handled differently:

* Note sure why the `toString()` methods are necessary; I think the default `toString()` method would return the same as the current implementation?
* Rename `_val` field/setters/getters to `fodValue` to make the purpose more clear
* Are the `fromInt()` methods actually used anywhere? My IDE didn't find any references. If they are not used, they should be removed, otherwise see next points.
* Rename `fromInt()` to `fromFoDValue()` to make purpose more clear
* Have the `fromFoDValue()` methods do a lookup instead of manual switch-based mapping. Some possible approaches:
     * Have the constructor store `fodValue` and `this` in a `Map`, such that the `fromFoDValue()` methods can simply do `return fodValueToEnumMap.get(fodValue)` (also handle unknown FoD values using one of the approaches here: https://stackoverflow.com/questions/11383649/key-existence-checking-utility-in-map)
     * Have the `fromFoDValue()` methods simply iterate over enum values (using Java 8 features) to find the matching enum value; see https://stackoverflow.com/questions/27807232/finding-enum-value-with-java-8-stream-api.
     * Given the Jackson annotations for serializing/deserializing FoD values from/to enum values, have the `fromFoDValue()` methods use Jackson to deserialize the FoD value to the corresponding enum value. Note that if `fromFoDValue()` is only used when deserializing FoD responses, then the `*Response` classes should just contain the proper enum fields instead of simple String/int/... fields, and then have Jackson handle deserialization of those enum fields based on the Jackson annotations on the enums.

**Comment by kadraman** [comment] 2023-07-27 14:23
Implemented in above commit to develop branch.

**Closed by kadraman** 2023-07-27 14:23 UTC
Labels: bug, fcli-fod
